# Generated by Django 5.0.2 on 2024-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('binaural_beats', 'Binaural Beats'), ('chimes', 'Chimes')], max_length=20)),
                ('duration', models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (25, '25 minutes')])),
                ('video_url', models.URLField()),
            ],
        ),
    ]
