# Generated by Django 5.0.2 on 2024-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.TextField(default='')),
                ('time', models.BigIntegerField(default=0)),
            ],
        ),
    ]
