# Generated by Django 5.0.2 on 2024-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='entry',
            name='val',
            field=models.TextField(default='255'),
        ),
    ]
