# Generated by Django 5.0.2 on 2024-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_user_alter_entry_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='activity',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='entry',
            name='val',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
