# Generated by Django 5.0.2 on 2024-04-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_activity_entry_mood_alter_entry_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='time',
            new_name='date',
        ),
    ]
